name: Run Nuke Bot

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

concurrency:
  group: nuke-bot-cluster
  cancel-in-progress: false

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          DISCORD_TOKENS: ${{ secrets.DISCORD_TOKENS }}
        run: python run.py
